name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to GitHub Docker Registry (GitHub Packages)
      - name: Log in to GitHub Packages Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/rent_prediction:0.1 .

      # Push the Docker image to GitHub Packages
      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/rent_prediction:0.1